from setuptools import setup, find_packages


setup(name='MyShell-OpenVoice',
      version='0.0.0',
      description='Instant voice cloning by MyShell.',
      long_description=open('README.md').read().strip(),
      long_description_content_type='text/markdown',
      keywords=[
            'text-to-speech',
            'tts',
            'voice-clone',
            'zero-shot-tts'
      ],
      url='https://github.com/myshell-ai/OpenVoice',
      project_urls={
        'Documentation': 'https://github.com/myshell-ai/OpenVoice/blob/main/docs/USAGE.md',
        'Changes': 'https://github.com/myshell-ai/OpenVoice/releases',
        'Code': 'https://github.com/myshell-ai/OpenVoice',
        'Issue tracker': 'https://github.com/myshell-ai/OpenVoice/issues',
      },
      author='MyShell',
      author_email='ethan@myshell.ai',
      license='MIT License',
      packages=find_packages(),

      python_requires='>=3.8',
      install_requires=[
            'librosa==0.10.0',
            'faster-whisper==0.9.0',
            'pydub==0.25.1',
            'wavmark==0.0.3',
            'numpy>=1.21.0',
            'eng_to_ipa==0.0.2',
            'inflect==7.0.0',
            'unidecode==1.3.7',
            'whisper-timestamped==1.14.2',
            'pypinyin==0.50.0',
            'cn2an==0.5.22',
            'jieba==0.42.1',
            'gradio>=3.50.0',
            'langid==1.1.6',
            'torch>=2.0.0',
            'soundfile>=0.12.1',
            'fastapi>=0.68.0',
            'uvicorn>=0.15.0',
            'python-multipart>=0.0.5',
            'pydantic>=1.8.0',
            'protobuf==3.20.0',
            'onnx==1.14.0',
            'onnxruntime==1.15.0',
            'trainer==0.0.20',
            'transformers==4.33.0',
            'scipy==1.11.2',
            'python-rtmidi==1.5.8',
            'PySide6==6.4.2',
      ],
      extras_require={
        "dev": [
            "pytest>=7.0.0",
            "black>=22.0.0",
            "isort>=5.0.0",
            "flake8>=4.0.0",
        ],
      },
      zip_safe=False
      )
