name: CI VocalClone

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  basic-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install basic dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest numpy scipy tqdm pathlib
        
    - name: Install core dependencies
      run: |
        # Installer seulement les dépendances essentielles
        pip install torch==2.1.0 --index-url https://download.pytorch.org/whl/cpu
        pip install torchaudio==2.1.0 --index-url https://download.pytorch.org/whl/cpu
        pip install transformers tqdm matplotlib
        
    - name: Lint with flake8
      run: |
        # Seulement vérifier les erreurs de syntaxe Python
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=venv*,models,**/bark/*,**/openvoice/*
        
    - name: Check structure and basic imports
      run: |
        # Vérifier que les fichiers principaux existent
        test -f src/main.py
        # Essayer d'importer les modules principaux
        python -c "import sys; sys.path.append('.'); import src.utils; print('Utils module available')"
        
    - name: Basic test
      run: |
        echo "Vérification de base réussie !" 